# If you want to overwrite this parameter, please copy default.yaml to customize.yaml. 
# And please edit coustomize.yaml.
---
resource:
  group:
    attributes:
      reject: []
  user:
    attributes:
      reject:
        - 'password_max_age'
        - 'password_min_age'
  package:
    attributes:
      reject: []
    param_ensure: true
  file:
    attributes:
      reject:
        - 'ctime'
        - 'mtime'
        - 'type'
    user_name: true
    group_name: true
    param_template: true
    param_source: true
  service:
    attributes:
      reject: []
    param_ensure: true
    param_enable: true
  yumrepo:
    attributes:
      reject: []
    param_ensure: true
    param_enabled: true
puppet:
  path: 'puppet'
facter:
  path: 'facter'
  allow:
    - 'osfamily'
    - 'operatingsystem'
    - 'operatingsystemmajrelease'
    - 'operatingsystemrelease'
    - 'hostname'
    - 'architecture'
verbose: true
ssh:
  user: 'root'
  options:
    :password: 'yourpassword'
